name: Check Point - Firewall approver demo. Protected branch.

on: 
  pull_request:
    branches: 
      - 'main'
  
jobs:
  output-tf-plan:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Run TF plan
        run: | 
          terraform init
          terraform plan -no-color 2>&1 | tee ${{ github.workspace }}/plan_output.txt
        env:
          TF_VAR_smart1_server: ${{secrets.TF_VAR_SMART1_SERVER}}
          TF_VAR_smart1_api_key: ${{secrets.TF_VAR_SMART1_API_KEY}}
          TF_VAR_smart1_cloud_id: ${{secrets.TF_VAR_SMART1_CLOUD_ID}}      
      - uses: actions/upload-artifact@v4
        with:
          name: TF plan output
          path: ${{ github.workspace}}/plan_output.txt

  apply-cp-policy:
    environment: prod
    runs-on: ubuntu-latest
    needs: output-tf-plan
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Apply TF CP policy to protected (main) policy
        run: | 
          terraform init
          terraform apply -auto-approve
        env:
          TF_VAR_smart1_server: ${{secrets.TF_VAR_SMART1_SERVER}}
          TF_VAR_smart1_api_key: ${{secrets.TF_VAR_SMART1_API_KEY}}
          TF_VAR_smart1_cloud_id: ${{secrets.TF_VAR_SMART1_CLOUD_ID}}

