name: Check Point - add TF plan output to PR comment

on: 
  pull_request:
    types: [opened]
    branches: 
      - 'main'
  
jobs:
  apply-cp-policy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Apply TF CP policy to limitedlayer1
        run: | 
          terraform init
          terraform plan -no-color 2>&1 | tee ${{ github.workspace }}/plan_output.txt
        env:
          TF_VAR_smart1_server: ${{secrets.TF_VAR_SMART1_SERVER}}
          TF_VAR_smart1_api_key: ${{secrets.TF_VAR_SMART1_API_KEY}}
          TF_VAR_smart1_cloud_id: ${{secrets.TF_VAR_SMART1_CLOUD_ID}}
      - name: Add TF plan output to PR
        uses: blinqas/tf-plan-pr-comment@v1
        with:
          output_file: ${{ github.workspace }}/plan_output.txt